[world]
name = "Dojo intro"
description = "A simple intro to Dojo."
seed = "dojo_intro"

[namespace]
default = "di"

[env]

# Sepolia Environment
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
account_address=  "0x0721834c557ce689176a2e66370585777ed82a916489dbe41d35acbe636cd55a"
private_key = ""

# Katana
#rpc_url = "http://localhost:5050/"
#account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
#private_key = ""

RUST_BACKTRACE=1

[writers]
"di" = ["di-game_system", "di-building_system", "di-wave_system"]
